<a href="https://colab.research.google.com/github/yusufdalva/ML_implementations/blob/torch_prod/PyTorch_fundamentals/PyTorch_Basics_Perceptrons_with_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Basics
This notebook shows applying basic calculations on PyTorch (numpy like operators). The implementation is originated from the lectures in https://www.udacity.com/course/deep-learning-pytorch--ud188. 

In [ ]:
# Importing PyTorch
import torch

## The Sigmoid Activation Function
As the first function, the sigmoid activation function is implemented in PyTorch. <br>The formulation is as follows: $\large{\sigma(x) = \frac{1}{1 + e^{-z}}}$

In [ ]:
def sigmoid_activation(z):
  """ Implementation of sigmoid activation function.
  Inputs:
  - z: torch.Tensor """
  return 1 / (1 + torch.exp(-z))

Now to test the sigmoid function and a perceptron in general, the linear discriminant function will be implemented, which basically performs: <br><br> $\large{(\sum_{i=1}^{n}{W_{i}.X_{i}) + b}}$, where n represents the number of features here.

In [ ]:
# Generation test input
torch.manual_seed(7) # Just like np.radom.seed in numpy

NO_OF_FEATURES = 5
NO_OF_SAMPLES = 1

X = torch.randn((NO_OF_SAMPLES,NO_OF_FEATURES)) # Single data sample for the beginning
W = torch.randn_like(X) # Random initial weights - Weights and input features have the same shape, weights for a single neuron
b = torch.randn((NO_OF_SAMPLES,1)) # Random initial bias

For the implementation of the perceptron, first the linear discriminant function is calculated. Then the sigmoid activation function is applied to this output. A figure illustrating this is shown below: <img src="https://i.stack.imgur.com/7mTvt.jpg"/><br> Here the function *f* is sigmoid activation function. Credit: https://i.stack.imgur.com/7mTvt.jpg

In [ ]:
def sigmoid_perceptron(X, W, b):
  sum = torch.matmul(X, W) + b
  return sigmoid_activation(sum)

In [ ]:
# Printing the inputs and computing the output
print('Features: ' + str(X))
print('Weights: ' + str(W))
print('Bias: ' + str(b))
y_hat = sigmoid_perceptron(X, W.T, b)
print('Output: ' + str(y_hat))

Features: tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
Weights: tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
Bias: tensor([[0.3177]])
Output: tensor([[0.1595]])


To change the shape of a tensor, the *view* function can be used. This function copies the original tensor and return the copy with the input shape: **torch.Tensor.view(input_shape)** - input is not a tuple, just the dimensions in order

In [ ]:
y_2 = sigmoid_activation(torch.sum(torch.matmul(X, W.view(NO_OF_FEATURES, NO_OF_SAMPLES))) + b)
print(y_2)

tensor([[0.1595]])


## Implementing a Hidden Layer
For illustration purposes, a hidden layer is implemented with tensor operations. The implemented network (Having two layers - one hidden, one output layer) uses sigmoid activation via **sigmoid_perceptron** function.

In [ ]:
# Generating initial weights for the hidden layer
torch.manual_seed(7)

NO_OF_FEATURES = 3
NO_OF_SAMPLES = 1

# Generating random input
X = torch.randn((NO_OF_SAMPLES, NO_OF_FEATURES))

# Specifiying the hidden layer properties
input_units = X.shape[1]
hidden_units = 2
output_units = 1

# Initialize the Weights and Biases for the network - Layer 1: 2 units(neurons), Layer 2(output): 1 unit(neuron)
W1 = torch.randn(input_units, hidden_units) # Weights for the first layer
W2 = torch.randn(hidden_units, output_units) # Weights for the second layer

# One bias term for each unit (neuron)
b1 = torch.randn((1, hidden_units))
b2 = torch.randn((1, output_units))

In [ ]:
# Computing the output
out_1 = sigmoid_perceptron(X, W1, b1)
print('Hidden layer output: ' + str(out_1))
out_final = sigmoid_perceptron(out_1, W2, b2)
print('Output of the model: ' + str(out_final))

Hidden layer output: tensor([[0.6813, 0.4355]])
Output of the model: tensor([[0.3171]])


## Tensor To Numpy Conversion
In this part the conversion between tensors and numpy arrays are shown. Initially a 5x4 matrix is created from random values from a normal distribution.

In [ ]:
import numpy as np

sample_arr = np.random.rand(5,4)
print('Type of the object: ' + str(type(sample_arr)))
print('Matrix contents:\n' + str(sample_arr))

Type of the object: <class 'numpy.ndarray'>
Matrix contents:
[[0.16920867 0.3604626  0.12064992 0.35487684]
 [0.04610831 0.02638534 0.16433284 0.02154747]
 [0.51000063 0.2774759  0.62431993 0.02006936]
 [0.2186867  0.63957207 0.49931445 0.22757941]
 [0.40159413 0.20058523 0.50815272 0.6627985 ]]


- Conversion from *Numpy array* to *torch.Tensor*

In [ ]:
sample_tensor = torch.from_numpy(sample_arr)
print('Type of the object: ' + str(type(sample_tensor)))
print('Matrix contents:\n' + str(sample_tensor))

Type of the object: <class 'torch.Tensor'>
Matrix contents:
tensor([[0.1692, 0.3605, 0.1206, 0.3549],
        [0.0461, 0.0264, 0.1643, 0.0215],
        [0.5100, 0.2775, 0.6243, 0.0201],
        [0.2187, 0.6396, 0.4993, 0.2276],
        [0.4016, 0.2006, 0.5082, 0.6628]], dtype=torch.float64)


- Conversion from *torch.Tensor* to *Numpy array*

In [ ]:
print('Type of the object: ' + str(type(sample_tensor.numpy())))
print('Matrix contents:\n' + str(sample_tensor.numpy()))

Type of the object: <class 'numpy.ndarray'>
Matrix contents:
[[0.16920867 0.3604626  0.12064992 0.35487684]
 [0.04610831 0.02638534 0.16433284 0.02154747]
 [0.51000063 0.2774759  0.62431993 0.02006936]
 [0.2186867  0.63957207 0.49931445 0.22757941]
 [0.40159413 0.20058523 0.50815272 0.6627985 ]]


- Both of the data structures (Tensor and ndarray) point to the same data, manipulation done by one of them effects the other one.

In [ ]:
sample_tensor.add_(5)
print('Tensor contents:\n' + str(sample_tensor))
print('Numpy array contents:\n' + str(sample_arr))

Tensor contents:
tensor([[5.1692, 5.3605, 5.1206, 5.3549],
        [5.0461, 5.0264, 5.1643, 5.0215],
        [5.5100, 5.2775, 5.6243, 5.0201],
        [5.2187, 5.6396, 5.4993, 5.2276],
        [5.4016, 5.2006, 5.5082, 5.6628]], dtype=torch.float64)
Numpy array contents:
[[5.16920867 5.3604626  5.12064992 5.35487684]
 [5.04610831 5.02638534 5.16433284 5.02154747]
 [5.51000063 5.2774759  5.62431993 5.02006936]
 [5.2186867  5.63957207 5.49931445 5.22757941]
 [5.40159413 5.20058523 5.50815272 5.6627985 ]]
